version: '3.8'

services:
  my-flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/rishabh/Desktop/File_upload/instance:/app/instance
      - /home/rishabh/Desktop/File_upload/uploads:/app/uploads
